language: perl
perl:
  - "5.22-thr"
  - "5.20-thr"
  - "5.18-thr"
  - "5.16-thr"
  - "5.14-thr"
  - "5.12-thr"
  - "5.10-thr"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install Test::Fatal Test::Pod --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -l -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
sudo: false
