language: perl
perl:
  - "5.20-thr"
  - "5.18-thr"
  - "5.16-thr"
  - "5.14-thr"
  - "5.12-thr"
  - "5.10-thr"
install:
  - "cpanm -n Test::Fatal Test::Pod"
  - "cpanm -n --installdeps ."
sudo: false
